# Pandas

In [28]:
import pandas as pd

In [29]:
dados = {
    'Nome': ['João', 'Maria', 'Pedro', 'Ana', 'Lucas'],
    'Idade': [28, 25, 35, 19, 42],
    'Departamento': ['TI', 'RH', 'TI', 'Financeiro', 'Vendas']
}

In [30]:
# Criando o dataframe
df1 = pd.DataFrame(dados)
df1

    Nome  Idade Departamento
0   João     28           TI
1  Maria     25           RH
2  Pedro     35           TI
3    Ana     19   Financeiro
4  Lucas     42       Vendas

In [31]:
print('============Inspecionando dados===========')
print('df.head():' , df1.head(3))
print("\n df.shape(linhas x colunas): ", df1.shape)

============Inspecionando dados===========
df.head():     Nome  Idade Departamento
0   João     28           TI
1  Maria     25           RH
2  Pedro     35           TI

 df.shape(linhas x colunas):  (5, 3)

In [32]:
print('============Operações===========')
# quase igual ao select * from table whare dep = 'TI'
df_ti = df1[df1['Departamento'] == 'TI']

print("Funcionarios de TI: ")
print(df_ti)

============Operações===========
Funcionarios de TI:
    Nome  Idade Departamento
0   João     28           TI
2  Pedro     35           TI

### usando arquivos csv

In [33]:
df2 = pd.read_csv("teste.csv")

In [34]:
print("primeiras linhas do arquivo")
df2.head(3)

primeiras linhas do arquivo

   id    nome departamento  salario  idade
0   1  Duarte   Engenharia     8500     27
1   2     Ana    Marketing     6200     24
2   3  Carlos   Engenharia     9100     30

In [35]:
print("tamanho do arquivo")
print(df2.shape)

tamanho do arquivo
(5, 5)

In [36]:
print("colunas")
print(df2.columns.to_list())

colunas
['id', 'nome', 'departamento', 'salario', 'idade']

In [37]:
print("informações sobre o dataframe")
df2.info()

informações sobre o dataframe
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            5 non-null      int64
 1   nome          5 non-null      object
 2   departamento  5 non-null      object
 3   salario       5 non-null      int64
 4   idade         5 non-null      int64
dtypes: int64(3), object(2)
memory usage: 332.0+ bytes

### Operações em pandas

In [39]:
print("Select e Where")

filtro = df2['departamento'] == 'Engenharia'
df_engenharia = df2.loc[filtro, ['nome', 'salario']]
print(df_engenharia)

Select e Where
     nome  salario
0  Duarte     8500
2  Carlos     9100

In [40]:
print("GROUP BY E AVG agupamento e calcular a média")

media_salarial = df2.groupby('departamento')['salario'].mean()
print(media_salarial)

GROUP BY E AVG agupamento e calcular a média
departamento
Engenharia    8800.0
Marketing     6000.0
RH            5400.0
Name: salario, dtype: float64

In [41]:
print("ORDER BY - Ordenação")
df_ordenado = df2.sort_values(by='salario', ascending=False)
print(df_ordenado[['nome', 'salario']])

ORDER BY - Ordenação
      nome  salario
2   Carlos     9100
0   Duarte     8500
1      Ana     6200
4     João     5800
3  Beatriz     5400

In [49]:
print("ALTER TABLE E ADD COLUMN")

df2['salario_com_bonus'] = df2['salario'] * 1.10
print(df2[['nome', 'salario', 'salario_com_bonus',]].head())

ALTER TABLE E ADD COLUMN
      nome  salario  salario_com_bonus
0   Duarte     8500             9350.0
1      Ana     6200             6820.0
2   Carlos     9100            10010.0
3  Beatriz     5400             5940.0
4     João     5800             6380.0

### Debugger

In [55]:
def calcular_media_idades(lista_idades):
    soma = 0
    for idade in lista_idades:
        if type(idade) == str:
            idade = int(idade)
        soma += idade

    if not len(lista_idades):
        return 0

    media = soma / len(lista_idades)
    return media

# cenario que funciona perfeito
# idades_equipe = [25, 30, 22, 27]
# print(f"Média 1: {calcular_media_idades(idades_equipe)}")

# cenario 2
idades_sem_ninguem = [25, 30, '22', 27]
print(f"Média 2: {calcular_media_idades(idades_sem_ninguem)}")

Média 2: 26.0

### Classes

In [56]:
class User:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def exibir_info(self):
        status = "Adulto" if self.age >= 10 else "Menor"
        print(f"Usuário: {self.name} | Idade: {self.age} | Status{status}")

# Instanciando objetos na memória
user1 = User("Duarte Junior", 27)
user2 = User("Ana Silva", 16)

# chamando os metodos

print("Sistemas de usuário")
user1.exibir_info()
user2.exibir_info()

Sistemas de usuário
Usuário: Duarte Junior | Idade: 27 | StatusAdulto
Usuário: Ana Silva | Idade: 16 | StatusAdulto

In [67]:
class User:
    def __init__(self, name, age, password):
        # publicos
        self.name = name
        self.age = age

        # privados
        self.__password = password

    def exibir_perfil(self):
        print(f"Perfil: Nome {self.name} | Idade: {self.age}")

    def verificar_senha(self, tentativa_senha):
        if tentativa_senha == self.__password:
            return "Acesso liberado!"
        else:
            return "Senha incorreta!"

professor = User("Duarte Junior", 27, "senha_secreta")
aluno = User("joão Silva", 20, "123456")

print("Sistemas de usuarios")
professor.exibir_perfil()
aluno.exibir_perfil()

print("Teste de encapsulamento")
print("Tentativa de login do João:")
print(aluno.verificar_senha("senha errada"))
print(aluno.verificar_senha("123456"))

Sistemas de usuarios
Perfil: Nome Duarte Junior | Idade: 27
Perfil: Nome joão Silva | Idade: 20
Teste de encapsulamento
Tentativa de login do João:
Senha incorreta!
Acesso liberado!